# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/guilbo_m/rendu/cpp/cpp_indie_studio

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/guilbo_m/rendu/cpp/cpp_indie_studio

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/guilbo_m/rendu/cpp/cpp_indie_studio/CMakeFiles /home/guilbo_m/rendu/cpp/cpp_indie_studio/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/guilbo_m/rendu/cpp/cpp_indie_studio/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Bomberman

# Build rule for target.
Bomberman: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Bomberman
.PHONY : Bomberman

# fast build rule for target.
Bomberman/fast:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/build
.PHONY : Bomberman/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/main.cpp.s
.PHONY : main.cpp.s

src/Controller/EventManager.o: src/Controller/EventManager.cpp.o

.PHONY : src/Controller/EventManager.o

# target to build an object file
src/Controller/EventManager.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Controller/EventManager.cpp.o
.PHONY : src/Controller/EventManager.cpp.o

src/Controller/EventManager.i: src/Controller/EventManager.cpp.i

.PHONY : src/Controller/EventManager.i

# target to preprocess a source file
src/Controller/EventManager.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Controller/EventManager.cpp.i
.PHONY : src/Controller/EventManager.cpp.i

src/Controller/EventManager.s: src/Controller/EventManager.cpp.s

.PHONY : src/Controller/EventManager.s

# target to generate assembly for a file
src/Controller/EventManager.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Controller/EventManager.cpp.s
.PHONY : src/Controller/EventManager.cpp.s

src/Map.o: src/Map.cpp.o

.PHONY : src/Map.o

# target to build an object file
src/Map.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Map.cpp.o
.PHONY : src/Map.cpp.o

src/Map.i: src/Map.cpp.i

.PHONY : src/Map.i

# target to preprocess a source file
src/Map.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Map.cpp.i
.PHONY : src/Map.cpp.i

src/Map.s: src/Map.cpp.s

.PHONY : src/Map.s

# target to generate assembly for a file
src/Map.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Map.cpp.s
.PHONY : src/Map.cpp.s

src/Objects/AGameObject.o: src/Objects/AGameObject.cpp.o

.PHONY : src/Objects/AGameObject.o

# target to build an object file
src/Objects/AGameObject.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Objects/AGameObject.cpp.o
.PHONY : src/Objects/AGameObject.cpp.o

src/Objects/AGameObject.i: src/Objects/AGameObject.cpp.i

.PHONY : src/Objects/AGameObject.i

# target to preprocess a source file
src/Objects/AGameObject.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Objects/AGameObject.cpp.i
.PHONY : src/Objects/AGameObject.cpp.i

src/Objects/AGameObject.s: src/Objects/AGameObject.cpp.s

.PHONY : src/Objects/AGameObject.s

# target to generate assembly for a file
src/Objects/AGameObject.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Objects/AGameObject.cpp.s
.PHONY : src/Objects/AGameObject.cpp.s

src/Objects/Wall.o: src/Objects/Wall.cpp.o

.PHONY : src/Objects/Wall.o

# target to build an object file
src/Objects/Wall.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Objects/Wall.cpp.o
.PHONY : src/Objects/Wall.cpp.o

src/Objects/Wall.i: src/Objects/Wall.cpp.i

.PHONY : src/Objects/Wall.i

# target to preprocess a source file
src/Objects/Wall.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Objects/Wall.cpp.i
.PHONY : src/Objects/Wall.cpp.i

src/Objects/Wall.s: src/Objects/Wall.cpp.s

.PHONY : src/Objects/Wall.s

# target to generate assembly for a file
src/Objects/Wall.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Objects/Wall.cpp.s
.PHONY : src/Objects/Wall.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Bomberman"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/Controller/EventManager.o"
	@echo "... src/Controller/EventManager.i"
	@echo "... src/Controller/EventManager.s"
	@echo "... src/Map.o"
	@echo "... src/Map.i"
	@echo "... src/Map.s"
	@echo "... src/Objects/AGameObject.o"
	@echo "... src/Objects/AGameObject.i"
	@echo "... src/Objects/AGameObject.s"
	@echo "... src/Objects/Wall.o"
	@echo "... src/Objects/Wall.i"
	@echo "... src/Objects/Wall.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

